- name: stop the server
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: Recursively remove app directory
  tags:
  - deployment
  ansible.builtin.file:
    path: "/app/*"
    state: absent
    #recurse: yes
    force: yes

- name: "download {{component}} application"
  tags:
  - deployment
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "extract {{component}} application"
  tags:
  - deployment
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes

- name: start the server
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted