- name: install go
  ansible.builtin.dnf:
    name: golang
    state: present
- name: dependencies and app build
  ansible.builtin.command: "{{item}}"
  loop:
  - go mod init dispatch
  - go get 
  - go build
  args:
    chdir: /app